# Generated by Django 4.2.7 on 2023-11-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('companyName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('isAvailed', models.BooleanField(default=False)),
                ('validityDate', models.DateField()),
                ('directUpload', models.BooleanField(default=True)),
                ('couponCode', models.CharField(max_length=255)),
                ('screenshots', models.ImageField(blank=True, null=True, upload_to='coupons/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('userImage', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('availedCouponsIds', models.ManyToManyField(blank=True, related_name='availed_coupons', to='Coupon.coupon')),
                ('uploadedCouponsIds', models.ManyToManyField(blank=True, related_name='uploaded_coupons', to='Coupon.coupon')),
            ],
        ),
    ]
