# Generated by Django 4.2.7 on 2023-11-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_screenshots/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/'),
        ),
    ]
