# Generated by Django 5.0 on 2023-12-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_messages',
            field=models.ManyToManyField(blank=True, related_name='chat_messages', to='Coupon.chatmessage'),
        ),
    ]
