# Generated by Django 5.0 on 2023-12-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0006_alter_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('senderUserid', models.IntegerField()),
                ('receiverUserid', models.IntegerField()),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='chat_messages',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chatWith',
            field=models.ManyToManyField(blank=True, related_name='chats', to='Coupon.userprofile'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
