# Generated by Django 5.0 on 2023-12-08 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0007_chat_remove_userprofile_chat_messages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='chatWith',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Coupon.userprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Coupon.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chat_messages',
            field=models.ManyToManyField(blank=True, related_name='chat_messages', to='Coupon.chatmessage'),
        ),
    ]
