# Generated by Django 5.0 on 2024-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0009_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
