# Generated by Django 3.2.23 on 2024-01-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0010_alter_userprofile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
