# Generated by Django 3.2.23 on 2024-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0011_alter_userprofile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='userId',
            field=models.CharField(max_length=255),
        ),
    ]
