# Generated by Django 5.0 on 2024-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0013_userprofile_email_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='userId',
            field=models.CharField(max_length=255),
        ),
    ]
